resolver: lts-20.2
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver:
#   url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/2.yaml

packages:
- .
