on: [push]

name: Build AoC executables
jobs:
  build-haskell:
    strategy:
      matrix:
        year: [2022]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build ${{ matrix.year }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: |
          stack build
        working-directory: ${{ matrix.year }}
      - name: Copy executable
        run: cp `stack path --local-install-root`/bin/aoc-${{ matrix.year }}.exe .
        shell: bash
        working-directory: ${{ matrix.year }}
        if: matrix.os == 'windows-latest'
      - name: Copy executable
        run: cp `stack path --local-install-root`/bin/aoc-${{ matrix.year }} .
        shell: bash
        working-directory: ${{ matrix.year }}
        if: matrix.os != 'windows-latest'
      - name: Test executable
        run: ./aoc-${{ matrix.year }} --help
        working-directory: ${{ matrix.year }}
      - uses: actions/upload-artifact@v3
        with:
          name: aoc-${{ matrix.year }}-${{ matrix.os }}
          path: ${{ github.workspace }}/${{ matrix.year }}/aoc-${{ matrix.year }}*
