on: [push]

name: Lint AoC code
jobs:
  hlint:
    strategy:
      matrix:
        year: [2022]
    name: HLint ${{ matrix.year }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v2

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v2
      with:
        path: '${{ matrix.year }}/'
        fail-on: warning
